# .github/workflows/build-windows.yml
name: Build Windows executable

# Lancer manuellement ou à chaque push sur main
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Mettre a jour pip & installer dependances
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyinstaller
          pip install --upgrade PySimpleGUI

      - name: Generer l'executable
        run: |
          pyinstaller --onefile --windowed gui.py

      - name: Publier l'artefact exe (local action)
        uses: ./.github/actions/upload-artifact
        with:
          name: gui-windows-exe
          path: dist/gui.exe
